"""add reservation id for cart product

Revision ID: 16f69d979f7d
Revises: cae89dd7df24
Create Date: 2023-01-25 14:44:37.672062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f69d979f7d'
down_revision = 'cae89dd7df24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('reservation_id', sa.String(), nullable=False, server_default=''))
    op.alter_column('carts', 'reservation_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'reservation_id')
    # ### end Alembic commands ###
