"""add dish id

Revision ID: 3713a8453e34
Revises: 16f69d979f7d
Create Date: 2023-01-25 22:12:31.247264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3713a8453e34'
down_revision = '16f69d979f7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('dish_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'dish_id')
    # ### end Alembic commands ###
