from product.domain.event_listeners import FoodFactoryDishListener
from product.domain.repositories import ProductRepository, FoodFactoryDishRepository
from product.infrastructure.amqp_food_factory_dish_listener import AmqpFoodFactoryDishListener
from product.infrastructure.http_food_factory_dish_repository import HttpFoodFactoryDishRepository
from product.infrastructure.sql_product_repository import SqlProductRepository
from shared.db import database

product_repository: ProductRepository = SqlProductRepository(database)
food_factory_dish_repository: FoodFactoryDishRepository = HttpFoodFactoryDishRepository()

food_factory_dish_listener: FoodFactoryDishListener = AmqpFoodFactoryDishListener(
    food_factory_dish_repository,
    product_repository
)
